CREATE DATABASE IF NOT EXISTS MeetupDB;
USE MeetupDB;

CREATE TABLE MeetupDB.Meetups (
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	Start DATETIME NOT NULL,
	Location VARCHAR(150) NOT NULL,
	Topic VARCHAR(150) NOT NULL,
	Description VARCHAR(1000) NOT NULL
);

CREATE TABLE MeetupDB.Users (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Birthdate DATETIME NOT NULL,
    Introduction VARCHAR(500),
    Avatar VARCHAR(1000),
    Email VARCHAR(150),
    PRIMARY KEY (ID)
);

CREATE TABLE MeetupDB.Statuses (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Value VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MeetupDB.MeetupReg (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    StatusId INTEGER NOT NULL,
    MeetupId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (StatusId) REFERENCES Statuses(ID),
	FOREIGN KEY (MeetupId) REFERENCES Meetups(ID),
	FOREIGN KEY (UserId) REFERENCES Users(ID)
);
