CREATE DATABASE IF NOT EXISTS MoviesDB;
USE MoviesDB;

CREATE TABLE MoviesDB.Directors (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
	Birthdate DATETIME NOT NULL,
	OscarWins INTEGER NOT NULL,
	TopMovies VARCHAR(1000) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MoviesDB.Actors (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Gender ENUM('F','M') NOT NULL,
    Birthdate DATETIME NOT NULL,
    PlaceOfBirth VARCHAR(100),
    OscarWins INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MoviesDB.Genres (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Value VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MoviesDB.Films (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Title VARCHAR(150) NOT NULL,
    ReleaseDate YEAR NOT NULL, 
    ActorsID VARCHAR(200) NOT NULL,
    DirectorsID VARCHAR(200) NOT NULL,
    GenreID VARCHAR(200) NOT NULL,
    PRIMARY KEY(ID),
      FOREIGN KEY (ActorsID) REFERENCES Actors(ID),
	    FOREIGN KEY (DirectorsID) REFERENCES Directors(ID),
	    FOREIGN KEY (GenreID) REFERENCES Genres(ID)
);
